package Duelyst.Model.Items;

public enum ItemName {
    TAJ_DANAEE, NAMOOS_SEPAR, BOW_OF_DAMOL, NOOSHDARO, TIR_DOSHAKH, PAR_SIMORGH, ELIXIR, MANA_POTION, INVINCIBILITY_POTION, DEATH_CURSE, RANDOM_DAMGE,
    TERROR_HOOD, BLADES_OF_AGILITY, KING_WISDOM, ASSASSINATION_DAGGER, POISONOUS_DAGGER, SHOCK_HAMMER, SOUL_EATER, GHOSL_TAMID, CHINESE_SWORD;

}
